<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_About us_vjs-poster</name>
   <tag></tag>
   <elementGuidId>0939ca71-13d5-42b4-8a1a-ba6e70456809</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.vjs-poster</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='example-video']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b89fb641-034c-4228-bb1c-14fdbb431794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vjs-poster</value>
      <webElementGuid>562b54de-46bb-4a6e-971e-8e35fac0f8fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>269211cc-fb99-4b57-b9d3-7e3c50877632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bba17978-429c-49d3-92e3-bb1b56d6b50b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;example-video&quot;)/div[@class=&quot;vjs-poster&quot;]</value>
      <webElementGuid>3b409a71-9df5-4e58-ae88-43fced8b4048</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='example-video']/div</value>
      <webElementGuid>96d4aa34-9e22-4e24-b7da-4aff265d5529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div</value>
      <webElementGuid>2c8649ee-31e6-4a20-ab24-03a494177a05</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
