<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contact Name_recipient-name</name>
   <tag></tag>
   <elementGuidId>347f5b08-5e41-4a95-acab-01bbd644dfa8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#recipient-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='recipient-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>36ff0a2b-3d4d-45d8-a8f6-d7abe8d839b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>aa86f0ec-060a-48ac-8301-419f64902afb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>525b290d-966e-4b10-b90d-107017c2d117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>recipient-name</value>
      <webElementGuid>c3c58568-821d-424b-baab-37c3131b3739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recipient-name&quot;)</value>
      <webElementGuid>8507db79-aea5-4ee1-bf4c-8baf0b8dcc07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='recipient-name']</value>
      <webElementGuid>b6d7fa4d-b561-43e6-9168-97da22cb13aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='exampleModal']/div/div/div[2]/form/div[2]/input</value>
      <webElementGuid>86343aa7-51cf-45d4-bcf3-6d74f6e295d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>951a2766-7e67-4417-bcd2-3629ec55b33c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'recipient-name']</value>
      <webElementGuid>6e4d583f-fd41-4579-b961-08567604e5dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
